site_name: Test Documentation
site_url: https://kenji-miyake.github.io/test-mkdocs-mike
repo_url: https://github.com/kenji-miyake/test-mkdocs-mike
edit_uri: edit/main/
docs_dir: docs
copyright: "Copyright &copy; 2021 Kenji Miyake"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  icon:
    logo: fontawesome/solid/car
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - awesome-pages
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - footnotes
  - mdx_math
  - mdx_truly_sane_lists: { nested_indent: 2 }
  - mdx_unimoji
  - plantuml_markdown: { server: "http://www.plantuml.com/plantuml", format: svg }
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - toc: { permalink: "#" }
